name: CI

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    paths-ignore:
      - ".git-blame-ignore-revs"
    branches: [main]
    # tags: ["v*"]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Run-Tests:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0 # Needed for the release tag // `git fetch --tags` will also work
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@32ffa16635ff8f19cc21ea253a987f0fdf29844c # v14
        with:
          java-version: openjdk@1.17
      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: "lts/*"
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@f530918424acb5cca3d46ccd8f6d6a35f5654fd3 # v1
      - name: Cache sbt
        uses: coursier/cache-action@288585e12960315492c10d496fafb65b57d9a89b # v6.3.3
      - name: Cache embedmongo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-embedmongo-4.14.0
          restore-keys: |
            ${{ runner.os }}-embedmongo-4.14.0
      ### Compile and TESTS ###
      - run: sbt -mem 2048 -J-Xmx5120m "test"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
