name: CI

on:
  workflow_dispatch:
  pull_request:
    branches-ignore:
      - "gh-pages"
  push:
    paths-ignore:
      - ".git-blame-ignore-revs"
    branches: [main]
    # tags: ["v*"]

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Run-Tests:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # https://github.com/japgolly/setup-everything-scala
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e3f713f2d8f53843e71c69a996d56f51aa9adfb9 # v2.14.1
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0 # Needed for the release tag // `git fetch --tags` will also work
      - name: Setup Java and Scala
        uses: olafurpg/setup-scala@32ffa16635ff8f19cc21ea253a987f0fdf29844c # v14
        with:
          java-version: openjdk@1.17
      - name: Setup Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: "lts/*"
      - name: Setup Scala.JS
        uses: japgolly/setup-scalajs@f530918424acb5cca3d46ccd8f6d6a35f5654fd3 # v1
      - name: Cache sbt
        uses: coursier/cache-action@c5ca79321d170b8a18c288d9cadc2a6037166d0f # v8.0.0
      - name: Cache embedmongo
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.embedmongo
          key: ${{ runner.os }}-embedmongo-4.14.0
          restore-keys: |
            ${{ runner.os }}-embedmongo-4.14.0
      ### Compile and TESTS ###
      - run: sbt -mem 2048 -J-Xmx5120m "test"
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
